### ISSUE TITLE
How to use with graphql-tools

### ISSUE THREAD

**Issue by Jscott388** [Soluto/graphql-to-mongodb#14]
I am trying to make things more simple and was wanting to get way form using the the plain graphql language and use graphql-tools from Apollo.

**Comment by daniele-zurico** [comment]
Jscott have you been able to use it in apollo-server? I'm trying to understand if I can use it

**Comment by Jscott388** [comment]
No I haven’t figured it out.

**Comment by yoavkarako** [comment]
I've put together a makeshift solution to integrate the package with `graphql-tools`.
__Unfortunately, it still needs work as the introspection doesn't update correctly, which screws with graphiql. It's more a prototype than anything else__

```
import { makeExecutableSchema, SchemaDirectiveVisitor } from "graphql-tools";

class FilterTypeDirective extends SchemaDirectiveVisitor {
    visitFieldDefinition(field) {
        const type = field.args[0].type;
        const queryArgs = getGraphQLQueryArgs(field.args[0].type);
        field.args = Object.keys(queryArgs).map(key => ({
            ...queryArgs[key],
            name: key
        }));
        field.resolve = getMongoDbQueryResolver(type, field.resolve);
    }
};

const typeDefs = `
type Name {
    first: String
    last: String
}

type Person {
    name: Name
    age: Int
}

type Query {
    people(type: Person): [Person] @FilterType
}
`;

const resolvers = {
    Query: {
        async people(filter, projection, options, obj, args, context) {
            return await context.db.collection('persons').find(filter, projection, options).toArray();
        }
    }
};

let schema = makeExecutableSchema({
    typeDefs,
    resolvers,
    schemaDirectives: {
        FilterType: FilterTypeDirective
    }
});
```

You need to add the `FilterTypeDirective ` directive over the main field, and add the main type as an argument to that field under the name `type`. The resolver is what you would put in place of the callback arg in the `getMongoDbQueryResolver`.

I hope to have a complete solution to this issue added to the package at some point due to `graphql-tools`'s popularity. Anyone familiar with `graphql-tools` who knows a better way to achieve this (Without screwing with the introspection/cleaner) is welcome to chip in.

**Comment by dohomi** [comment]
I came across this package - it would be nice to see an integration with graphql-yoga to build it directly upon a server. I wrote a small package with authentication, subscription and CRUD here: https://github.com/dohomi/graphql-yoga-mongodb
It would be nice to extend it with `graphql-to-mongodb` just for better usability out of the box

**Comment by ansarizafar** [comment]
Any update on this issue?

**Comment by yoavkarako** [comment]
https://github.com/Soluto/graphql-to-mongodb/pull/37 done
