### ISSUE TITLE
Typo in README.md with request for clarification

### ISSUE THREAD

**Issue by shadercode** [Soluto/graphql-to-mongodb#43]
README.md describes an aspect of the main use case as:

> To implement, we'll define the peron query field in our GraphQL scheme like so:
> 
> ```
> people: {
> ...
> }
> ```

I assume "peron" was intended to be written as "person", but would you please describe a little bit more about this "person query field" and why it is named "people" as opposed to "person"?  Thanks!

**Comment by yoavkarako** [comment]
Your assumption is correct. Missed it when editing.
The field's type is a list, so the plural form of person made sense.

`people query field` refers to the field to which the package's middleware is added — 'query` because the field is a query rather than a mutation.

These aren't conventions usage of the package requires adherence to, as it's generally not opinionated.
